name: obot_completion_generator
description: A completion generator for ObotAI InputCompletion.
version: 1.0.2
repository: https://github.com/obot-ai/obot-completion-generator-dart

environment:
  sdk: ^3.3.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
  mockito: ^5.4.4
