name: obot_completion_generator
description: A completion generator for ObotAI InputCompletion.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
  mockito: ^5.4.4
